export default function handler(req, res) {
  res.status(200).json({
    data: [
      {
        Index_Code: 42,
        Index_Name: " Telecom",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 1.36,
        color: "bg-[#009900]",
      },
      {
        Index_Code: 35,
        Index_Name: " Basic Materials",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 1.05,
        color: "bg-[#009900]",
      },
      {
        Index_Code: 15,
        Index_Name: " Auto",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.98,
        color: "bg-[#00b300]",
      },
      {
        Index_Code: 6,
        Index_Name: " FMCG",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.85,
        color: "#00b300",
      },
      {
        Index_Code: 36,
        Index_Name: " Consumer Disc.",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.8,
        color: "#00b300",
      },
      {
        Index_Code: 43,
        Index_Name: " Utilities",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.8,
        color: "#00b300",
      },
      {
        Index_Code: 21,
        Index_Name: " Realty",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.74,
        color: "#00b300",
      },
      {
        Index_Code: 17,
        Index_Name: " Oil Gas",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.67,
        color: "#00b300",
      },
      {
        Index_Code: 41,
        Index_Name: " Energy",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.62,
        color: "#00b300",
      },
      {
        Index_Code: 40,
        Index_Name: " Industrials",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.6,
        color: "#00b300",
      },
      {
        Index_Code: 9,
        Index_Name: " Healthcare",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.53,
        color: "#00b300",
      },
      {
        Index_Code: 16,
        Index_Name: " Metal",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.44,
        color: "#00b300",
      },
      {
        Index_Code: 37,
        Index_Name: " Finance",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.43,
        color: "#00b300",
      },
      {
        Index_Code: 8,
        Index_Name: " Consumer Durables",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.41,
        color: "#00b300",
      },
      {
        Index_Code: 22,
        Index_Name: " Power",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.35,
        color: "#00b300",
      },
      {
        Index_Code: 7,
        Index_Name: " Capital Goods",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.32,
        color: "#00b300",
      },
      {
        Index_Code: 14,
        Index_Name: " Bankex",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.29,
        color: "#00b300",
      },
      {
        Index_Code: 29,
        Index_Name: " Infra",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.19,
        color: "#00b300",
      },
      {
        Index_Code: 11,
        Index_Name: " Teck",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.05,
        color: "#00b300",
      },
      {
        Index_Code: 5,
        Index_Name: " IT",
        Date: "0001-01-01T00:00:00",
        Close: null,
        Exchange: "BSE",
        Volume: null,
        CloseStart: null,
        CloseEnd: null,
        ClosePercent: 0.02,
        color: "#00b300",
      },
    ],
    period: [
      {
        label: "1D",
        value: "1D",
      },
      {
        label: "1W",
        value: "1W",
      },
      {
        label: "1M",
        value: "1M",
      },
      {
        label: "3M",
        value: "3M",
      },
      {
        label: "6M",
        value: "6M",
      },
      {
        label: "12M",
        value: "12M",
      },
      {
        label: "2Y",
        value: "2Y",
      },
      {
        label: "3Y",
        value: "3Y",
      },
    ],
    selected_period: {
      label: "1D",
      value: "1D",
    },
  });
}
